In [2]:
import numpy as np

from sklearn.linear_model import Perceptron

#AND
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])

and_gate = Perceptron(tol=1e-3, random_state=0)
and_gate.fit(X, y)

x = np.array([[0,0],[0,1],[1,0],[1,1]])
print('Predicted values for AND \nx = [[0,0],[0,1],[1,0],[1,1]]')
print(and_gate.predict(x))

Predicted values for AND 
x = [[0,0],[0,1],[1,0],[1,1]]
[0 0 0 1]


In [3]:
#OR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,1])

or_gate = Perceptron(tol=1e-3, random_state=0)
or_gate.fit(X, y)

x = np.array([[0,0],[0,1],[1,0],[1,1]])
print('Predicted values for OR \nx = [[0,0],[0,1],[1,0],[1,1]]')
print(or_gate.predict(x))

Predicted values for OR 
x = [[0,0],[0,1],[1,0],[1,1]]
[0 1 1 1]


In [4]:
#XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,0])

xor_gate = Perceptron(tol=1e-3, random_state=0)
xor_gate.fit(X, y)

x = np.array([[0,0],[0,1],[1,0],[1,1]])
print('Predicted values for XOR \nx = [[0,0],[0,1],[1,0],[1,1]]')
print(xor_gate.predict(x))

Predicted values for XOR 
x = [[0,0],[0,1],[1,0],[1,1]]
[0 0 0 0]
